### ISSUE TITLE
MU SAMSUNG TV

### ISSUE THREAD

**Issue by veki978** [marttiku/node-red-contrib-samsung-tv-mk#1]
Hi.
I have problem with my TV. 
Every time when I send the command on TV, appears "access permission" pop up window. I grant access (press "Allow") and with another command all over again. In details for this new device is only "allow video streaming to TV".  Also I disable "new device acknowledgement" in TV.
How can I find token?

PS.
On "isalive" node output ON and OFF are replaced.

Thanks,
Veki

**Comment by cs33lm** [comment]
Hi Veki, 

i submitted a PR for the output issue. 
You can find the token in the node red log itself. As I use docker, I had to check the STDOUT/ERR output of the container. 

The location of your log depends on how you run node-red, maybe your solution can be found here:
[https://discourse.nodered.org/t/where-can-i-read-node-red-logs/7698/10](https://discourse.nodered.org/t/where-can-i-read-node-red-logs/7698/10)

Cheers, 
Chris

**Comment by veki978** [comment]
That is my log.
`28 Apr 16:43:23 - [info] [debug:9524ee0e.fc29c] KEY_DOWN
TV is avaliable
error  { RangeError: Invalid WebSocket frame: invalid status code 1005
    at Receiver.controlMessage (/home/pi/.node-red/node_modules/samsung-tv-control/node_modules/ws/lib/receiver.js:449:18)
    at Receiver.getData (/home/pi/.node-red/node_modules/samsung-tv-control/node_modules/ws/lib/receiver.js:335:42)
    at Receiver.startLoop (/home/pi/.node-red/node_modules/samsung-tv-control/node_modules/ws/lib/receiver.js:138:22)
    at Receiver._write (/home/pi/.node-red/node_modules/samsung-tv-control/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Receiver.Writable.write (_stream_writable.js:294:11)
    at TLSSocket.socketOnData (/home/pi/.node-red/node_modules/samsung-tv-control/node_modules/ws/lib/websocket.js:864:35)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at TLSSocket.Readable.push (_stream_readable.js:220:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) [Symbol(status-code)]: 1002 }
`
Help, please. :)

**Comment by structure7** [comment]
It looks like Toxblh [just added](https://github.com/Toxblh/samsung-tv-control/issues/3#issuecomment-496693099) the ability to get the token on the first send. Hopefully this can be included in the node. Thanks!

**Comment by structure7** [comment]
@veki978 Not sure if this helps, but I had to run `node-red-start -v` and when I triggered any TV key using the node, I get a log output message containing about 15 line. Look for "token" which is an 8-digit number. FYI, if you currently have your node configured with token (which is the wrong one) you might see two token entries: the one you entered (incorrect) and the correct one.

**Comment by Toxblh** [comment]
In the first "init" connection need to get a token from logs - or .getToken return token in a callback. Need to save it for the future. If you will do someone other operations it will ask token every time. 

But I didn't use node-red. Can you save the token for storage for the first-time installation?

And I can do what will save token for future in the instance as well. But after reload that will ask again (token will in memory)

**Comment by worksasdesigned** [comment]
Same issue. I cant find that damn token.
Running Node red as Redmatic. I have checked all debug levels in node red, but no log file including this token anywhere.

**Comment by matteo-tonini** [comment]
I had the same problem.

I solved by adding a new line of code in file **samsung.js**.
See below.

```
.then(() => device.remote.sendKey(String(key), function (err, res) {
  if (err) {
      node.warn(err);
  } else {
      //ADD THE FOLLOWING LINE:
      node.warn(res);
      //
  }
}))
```

Add the line, then stop node red and start it again.
After you grant permission on the TV, the object containing the token will be printed right in the node red debug console.

**Comment by PaytonPeterson** [comment]
@MTxx87 - Thank you so much for sharing this on here. **This absolutely fixed my issue** and I am so thankful to you for it. Spent at least 6 hours trying to find the token in my debug logs until I stumbled across your comment.

**Comment by worksasdesigned** [comment]
Thank you. This solved my problem. 
Has anyone got the AppList? All app IDs I tried didn't work so far.

**Comment by Lennypit** [comment]
i had troubles to get the token 
then i install wscat "npm install -g wscat"
then "wscat -n -c https://TVIP:8002/api/v2/channels/samsung.remote.control?name=aW9Ccm9rZXI="
then i get the Information "< {"data":{"clients":[{"attributes":{"name":"c3ZlbnJlbW90ZQ=="},"connectTime":1550138105298,"deviceName":"c3ZlbnJlbW90ZQ==","id":"e28eb78-6ae-4a16-909c-93f24d2b641c","isHost":false}],"id":"e28eb78-6ae-4a16-909c-93f24d2b641c","token":"16347308"},"event":"ms.channel.connect"}"
so my token is **16347308** and it works with node red
